### ISSUE TITLE
微博登录失败，说是没有权限？

### ISSUE THREAD

**Issue by sendtion** [ElbbbirdStudio/ESSocialSDK#4]
`Writing exception to parcel
java.lang.SecurityException: No permission to write APN settings
at com.android.providers.telephony.TelephonyProvider.checkPermission(TelephonyProvider.java:2046)
at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:1541)
at android.content.ContentProvider.query(ContentProvider.java:1027)
at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
at android.os.Binder.execTransact(Binder.java:453)`

**Comment by sendtion** [comment]
好像是使用wifi没事，使用数据流量出这个问题

**Comment by sendtion** [comment]
不对，是打包后发生异常，数据和wifi都会异常。我看了混淆文件，应该没问题啊
